/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: 'lf',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  // this is duplicating imports for some reason
  // importOrder: [
  //   "^(react/(.*)$)|^(react$)",
  //   "^(next/(.*)$)|^(next$)",
  //   "<THIRD_PARTY_MODULES>",
  //   "",
  //   "^types$",
  //   "^~/types/(.*)$",
  //   "^~/config/(.*)$",
  //   "^~/lib/(.*)$",
  //   "^~/hooks/(.*)$",
  //   "^~/components/ui/(.*)$",
  //   "^~/components/(.*)$",
  //   "^~/styles/(.*)$",
  //   "^~/app/(.*)$",
  //   "",
  //   "^[./]",
  // ],
  // importOrder: ["^@(.*)$", "^~/(.*)$", "^[./]"],
  // importOrderSeparation: true,
  // importOrderSortSpecifiers: true,
  printWidth: 120,
  tailwindFunctions: ['cn', 'clsx', 'cva'],
  plugins: ['prettier-plugin-tailwindcss'],
}
