version: '3'

dotenv: ['.env']
silent: true

tasks:
  build:
    cmds:
      - docker build -t powerstack-hasura:local .

  run:
    cmds:
      - docker run --name powerstack-hasura --env-file .env -p 3300:3300 -d powerstack-hasura:local

  id:
    cmds:
      - docker ps -aqf "name=^powerstack-hasura$"

  stop:
    cmds:
      - docker stop powerstack-hasura

  start:
    cmds:
      - docker start powerstack-hasura

  restart:
    cmds:
      - docker restart powerstack-hasura

  kill:
    cmds:
      - docker kill powerstack-hasura






