version: '3'

dotenv: ['.env']
silent: true

tasks:
  build:
    cmds:
      - docker build -t powerstack-remix:local .

  run:
    cmds:
      - docker run --name powerstack-remix --env-file .env -p 3000:3303 -d powerstack-remix:local

  id:
    cmds:
      - docker ps -aqf "name=^powerstack-remix$"

  stop:
    cmds:
      - docker stop powerstack-remix

  start:
    cmds:
      - docker start powerstack-remix

  restart:
    cmds:
      - docker restart powerstack-remix

  kill:
    cmds:
      - docker kill powerstack-remix
