import { Coin } from '../_legacy/types/engine.type'

export const coin_list: Coin[] = [
  {
    name: 'Bitcoin',
    symbol: 'BTC',
    usd_price: '0',
    coingecko_key: 'bitcoin',
    price_change_1h: '...',
  },
  {
    name: 'Ethereum',
    symbol: 'ETH',
    usd_price: '0',
    coingecko_key: 'ethereum',
    price_change_1h: '...',
  },
  {
    name: 'Grin',
    symbol: 'GRIN',
    usd_price: '0',
    coingecko_key: 'grin',
    price_change_1h: '...',
  },
  {
    name: 'Mina',
    symbol: 'MINA',
    usd_price: '0',
    coingecko_key: 'mina-protocol',
    price_change_1h: '...',
  },
  {
    name: 'Solana',
    symbol: 'SO',
    usd_price: '0',
    coingecko_key: 'solana',
    price_change_1h: '...',
  },
  {
    name: 'Polkadot',
    symbol: 'DOT',
    usd_price: '0',
    coingecko_key: 'polkadot',
    price_change_1h: '...',
  },
  {
    name: 'Binance Coin',
    symbol: 'BNB',
    usd_price: '0',
    coingecko_key: 'binancecoin',
    price_change_1h: '...',
  },
  {
    name: 'Avalanche',
    symbol: 'AVAX',
    usd_price: '0',
    coingecko_key: 'avalanche-2',
    price_change_1h: '...',
  },
  {
    name: 'Basic Attention Token',
    symbol: 'BAT',
    usd_price: '0',
    coingecko_key: 'basic-attention-token',
    price_change_1h: '...',
  },
  {
    name: 'Immutable X',
    symbol: 'IMX',
    usd_price: '0',
    coingecko_key: 'immutable-x',
    price_change_1h: '...',
  },
  {
    name: 'Flow',
    symbol: 'FLOW',
    usd_price: '0',
    coingecko_key: 'flow',
    price_change_1h: '...',
  },
  {
    name: 'EOS',
    symbol: 'EOS',
    usd_price: '0',
    coingecko_key: 'eos',
    price_change_1h: '...',
  },
  {
    name: 'Aave',
    symbol: 'AAVE',
    usd_price: '0',
    coingecko_key: 'aave',
    price_change_1h: '...',
  },
]
