name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Create local directory for report
        run: mkdir /tmp/artifacts
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install
      
      - name: Run Lighthouse
        run: |
          yarn add global @lhci/cli@0.9.x
          yarn run lhci autorun --config=./lighthouserc-ci.js
        with:
          outputDirectory: /tmp/artifacts
      
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      
      # - name: run Lighthouse CI
      #   id: lighthouse_audit
      #   with:
      #     uploadArtifacts: true
      #     temporaryPublicStorage: true
      #   run: |
      #     yarn add global && yarn add global @lhci/cli@0.9.x
      #     yarn run lhci autorun --config=./lighthouserc-ci.js

      # - name: Format lighthouse score
      #   id: format_lighthouse_score
      #   uses: actions/github-script@v5
      #   with:
      #     script: | 
          
      #       const lighthouseCommentMaker = require('./.github/workflows/lighthouseCommentMaker.js');
      #       const lighthouseOutputs = {
      #         manifest: ${{ steps.lighthouse_audit.outputs.manifest }},
      #         links: ${{ steps.lighthouse_audit.outputs.links }}
      #       };
      #       const comment = lighthouseCommentMaker({ lighthouseOutputs });
      #       core.setOutput("comment", comment);
      # - name: Add Lighthouse stats as comment
      #   id: comment_to_pr
      #   uses: marocchino/sticky-pull-request-comment@v2.0.0
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      #     header: lighthouse
      #     message: ${{ steps.format_lighthouse_score.outputs.comment }}