name: Vercel Preview URL Lighthouse Audit
on: push
jobs:
  generate_lighthouse_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        id: loading_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN}}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            Running Lighthouse audit...

      - name: Declare Github variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=github_branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=github_sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=github_sha::$(git rev-parse HEAD)"

      - name: test step
        run: |
          echo "Branch: ${{ steps.vars.outputs.github_branch }}"
          echo "Sha: ${{ steps.vars.outputs.github_sha }}"
          echo "Sha short: ${{ steps.vars.outputs.github_sha_short }}"

      - name: Capture Vercel URL
        id: vercel_preview_url
        uses: zentered/vercel-preview-url@v1.0.0
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: 'team_2b2sAtsGvmJrVpaHsBqigXVu'
          vercel_project_id: 'prj_oRkgj6YBJ2hfDswwwu8mmVA12Ahv'

      - name: Wait for Vercel deployment
        uses: UnlyEd/github-action-await-vercel@v1.2.14
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
          timeout: 180 # Wait for x seconds before failing

      - name: Audit preview URL with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v9
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ steps.vars.outputs.github_sha }}
        with:
          urls: |
            https://${{ steps.vercel_preview_url.outputs.preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
          script: |
            const result = ${{ steps.lighthouse_audit.outputs.manifest }}[0].summary
            const links = ${{ steps.lighthouse_audit.outputs.links }}
            const formatResult = (res) => Math.round((res * 100))
            Object.keys(result).forEach(key => result[key] = formatResult(result[key]))
            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴'
            const comment = [
                `⚡️ [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:`,
                '| Category | Score |',
                '| --- | --- |',
                `| ${score(result.performance)} Performance | ${result.performance} |`,
                `| ${score(result.accessibility)} Accessibility | ${result.accessibility} |`,
                `| ${score(result['best-practices'])} Best practices | ${result['best-practices']} |`,
                `| ${score(result.seo)} SEO | ${result.seo} |`,
                `| ${score(result.pwa)} PWA | ${result.pwa} |`,
                ' ',
                `*Lighthouse ran on [${Object.keys(links)[0]}](${Object.keys(links)[0]})*`
            ].join('\n')
             core.setOutput("comment", comment);

      - name: Add report to PR
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN}}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}
