name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: |
          yarn add global @lhci/cli@0.9.x
          yarn run build

      - name: Run Audit Lighthouse
        run: |
          yarn add global && yarn add global @lhci/cli@0.9.x
          yarn lhci autorun --config=./lighthouserc-ci.js 
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
     
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'