name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir /tmp/artifacts
      - name: Run lighthouse use Node.js 16
        uses: actions/setup-node@v3
        with:
          outputDirectory: /tmp/artifacts
          node-version: 16
      - name: yarn install
        run: |
          yarn add global @lhci/cli@0.9.x
          yarn run build
      - name: run Lighthouse CI 
        run: |
          yarn add global && yarn add global @lhci/cli@0.9.x
          yarn run lhci autorun --config=./lighthouserc-ci.js 
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts